# Generated by Django 6.0.6 on 2026-06-24 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('wait', '답변 대기'), ('progress', '처리중'), ('done', '답변 완료')], default='wait', max_length=20)),
                ('is_private', models.BooleanField(default=True)),
                ('email_on_answer', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_inquiry',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('content', models.TextField()),
                ('reference_url', models.URLField(blank=True)),
                ('is_notice', models.BooleanField(default=False)),
                ('is_comment_blocked', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_post',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.communityinquiry')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.communitypost')),
            ],
            options={
                'db_table': 'community_comment',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='communityinquiry',
            index=models.Index(fields=['status', 'is_deleted', '-created_at'], name='comm_inq_status_idx'),
        ),
        migrations.AddIndex(
            model_name='communityinquiry',
            index=models.Index(fields=['author', 'is_deleted', '-created_at'], name='comm_inq_author_idx'),
        ),
        migrations.AddIndex(
            model_name='communityinquiry',
            index=models.Index(fields=['is_private', 'is_deleted', '-created_at'], name='comm_inq_private_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['is_deleted', '-created_at'], name='comm_post_del_created_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['author', 'is_deleted', '-created_at'], name='comm_post_author_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['is_notice', 'is_deleted', '-created_at'], name='comm_post_notice_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['post', 'is_deleted', 'created_at'], name='comm_cmt_post_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['inquiry', 'is_deleted', 'created_at'], name='comm_cmt_inq_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['author', 'is_deleted', 'created_at'], name='comm_cmt_author_idx'),
        ),
        migrations.AddConstraint(
            model_name='communitycomment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('inquiry__isnull', True), ('post__isnull', False)), models.Q(('inquiry__isnull', False), ('post__isnull', True)), _connector='OR'), name='community_comment_one_target'),
        ),
    ]
